#
# Module manifest for module 'LithnetMiisAutomation'
#
# Generated by: Ryan Newington
#
# Generated on: 28/08/2015
#

@{

# Version number of this module.
ModuleVersion = '$version$'

# ID used to uniquely identify this module
GUID = '0b36101d-43c9-41c6-b9d2-7209623829a3'

# Author of this module
Author = 'Ryan Newington'

# Company or vendor of this module
CompanyName = 'Lithnet'

# Copyright statement for this module
Copyright = ''

# Description of the functionality provided by this module
Description = 'Lithnet PowerShell Module for FIM/MIM Synchronization Service'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Name of the Windows PowerShell host required by this module
PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
PowerShellHostVersion = ''

# Minimum version of the .NET Framework required by this module
DotNetFrameworkVersion = '4.5'

# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = ''

# Processor architecture (None, X86, Amd64, IA64) required by this module
ProcessorArchitecture = 'Amd64'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = 'Lithnet.Miiserver.Client.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module
# ScriptsToProcess = @('RegisterResolver.ps1')

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
#FormatsToProcess = @("ManagementAgent.format.ps1xml", "Attribute.format.ps1xml")

# Modules to import as nested modules of the module specified in ModuleToProcess
NestedModules = @('Lithnet.Miiserver.Automation.dll', 'LithnetMIISAutomation.psm1')

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module
ModuleList = @()

# List of all files packaged with this module
FileList = @()

# Private data to pass to the module specified in ModuleToProcess
PrivateData = ''

}